# Generated by Django 3.0.5 on 2021-12-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211203_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watching', to='recipes.Recipe'),
            preserve_default=False,
        ),
    ]
