# Generated by Django 3.0.5 on 2021-12-04 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20211203_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='amount'),
            preserve_default=False,
        ),
    ]
