# Generated by Django 3.0.5 on 2021-12-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20211205_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='recipe',
        ),
        migrations.AddField(
            model_name='cart',
            name='recipe',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='recipes.Recipe'),
            preserve_default=False,
        ),
    ]
