# Generated by Django 3.0.5 on 2021-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20211209_1014'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient', 'amount'), name='unique_ingredient_portion'),
        ),
    ]
