# Generated by Django 3.0.5 on 2021-12-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211208_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отмечает пользователя как активного. Уберите галочку вместо удаления пользователя', verbose_name='Активный'),
        ),
    ]
